# SOPS configuration for encrypted secrets management.
# The age public key below must match the private key on the deployment target
# (Raspberry Pi) at ~/.config/sops/age/keys.txt
#
# Setup:
#   1. Generate keypair: age-keygen -o ~/.config/sops/age/keys.txt
#   2. Paste the public key below
#   3. Encrypt:  sops encrypt --input-type dotenv --output-type dotenv email.env > email.enc.env
#   4. Decrypt:  sops decrypt --input-type dotenv --output-type dotenv email.enc.env > email.env
#   5. Edit:     sops email.enc.env

creation_rules:
  - path_regex: \.enc\.env$
    age: "age1pu66zjfcnlnmjmle4mt22xq6eg99jkjjfla5cztf6terjw64f5sqxx65xr"
